# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title.html
plugins: [jekyll-paginate]

source: '.'
destination: '_site'
collections_dir: '.'
plugins_dir: '_plugins'
layouts_dir: '_layouts'
data_dir: '_data'
includes_dir: '_includes'

#timezone:			'Asia/Chongqing'
encoding:           'utf-8'

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

markdown: kramdown
highlighter: rouge

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
